/**
 * Abstract base class and shared enumerations for all MEOS temporal types.
 *
 * Temporal values in MEOS represent quantities that evolve over time. Each
 * value is internally one of three subtypes:
 *   Instant      -> a single (value, timestamp) pair
 *   Sequence     -> an ordered list of instants with an interpolation mode
 *   SequenceSet  -> a set of disjoint sequences
 *
 * The Temporal<V> class wraps a raw WASM pointer (_inner) and exposes the
 * generic temporal API defined in meos.h. Concrete subclasses (TBool, TInt,
 * TFloat, …) add value-type-specific operations on top.
 *
 * All C wrapper calls in this file go through the local call<T>() helper,
 * which delegates to Emscripten's Module.ccall(). The _w suffix wrappers are
 * either generated by FunctionsGenerator (e.g. temporal_copy_w) or
 * hand-written in res/bindings_c_header.txt (e.g. temporal_as_hexwkb_w,
 * temporal_as_mfjson_w, temporal_instant_n_w, temporal_duration_us_w).
 */

import { getModule } from '../../runtime/meos';
import type { Ptr, TimestampTz } from '../../functions/functions.generated';
import { ptrArgType, ptrArgVal, callPtr } from '../../functions/functions.generated';

function call<T>(
	name: string,
	ret: 'number' | 'bigint' | 'string' | 'boolean' | null,
	argTypes: ('number' | 'string' | 'boolean' | 'bigint')[],
	args: unknown[]
): T {
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	return getModule().ccall(name, ret as any, argTypes as any, args) as T;
}

/**
 * Interpolation mode of a temporal sequence.
 *
 * MEOS supports four modes:
 *   None      -> used for Instant subtypes (no interpolation concept)
 *   Discrete  -> values are defined only at the listed instants
 *   Stepwise  -> value is constant between instants (step function)
 *   Linear    -> value is linearly interpolated between instants (TFloat only)
 */
export enum TInterpolation {
	None = 'None',
	Discrete = 'Discrete',
	Stepwise = 'Step',
	Linear = 'Linear',
}

export namespace TInterpolation {
	/**
	 * Parses the interpolation string returned by MEOS (e.g. "Linear",
	 * "Step", "Discrete") into the corresponding enum member.
	 */
	export function fromString(s: string): TInterpolation {
		switch (s.toLowerCase()) {
			case 'discrete':
				return TInterpolation.Discrete;
			case 'linear':
				return TInterpolation.Linear;
			case 'step':
			case 'stepwise':
				return TInterpolation.Stepwise;
			default:
				return TInterpolation.None;
		}
	}
}

/**
 * Subtype of a temporal value.
 *
 * A temporal can be stored as one of four subtypes depending on the WKT
 * string passed to the constructor:
 *   Instant     -> `"true@2001-01-01"`
 *   InstantSet  -> `"{true@2001-01-01, false@2001-01-02}"`  (discrete)
 *   Sequence    -> `"[true@2001-01-01, false@2001-01-02]"`
 *   SequenceSet -> `"{[true@2001-01-01, false@2001-01-02], [true@2001-01-03]}"`
 */
export enum TemporalType {
	Instant = 'Instant',
	InstantSet = 'InstantSet',
	Sequence = 'Sequence',
	SequenceSet = 'SequenceSet',
}

export namespace TemporalType {
	/**
	 * Infers the subtype from the WKT string representation by inspecting
	 * the opening characters, matching the same logic as MEOS internally.
	 *
	 * The "Interp=Stepwise;" prefix indicates a stepwise sequence or
	 * sequence set; square/round brackets denote a sequence; a leading brace
	 * followed by a bracket is a sequence set; otherwise it is an instant or
	 * instant set.
	 */
	export function fromWKT(wkt: string): TemporalType {
		if (wkt.startsWith('Interp=Stepwise;')) {
			return wkt.startsWith('{', 16) ? TemporalType.SequenceSet : TemporalType.Sequence;
		}
		if (wkt.startsWith('[') || wkt.startsWith('(')) return TemporalType.Sequence;
		if (wkt.startsWith('{')) {
			return wkt.startsWith('[', 1) || wkt.startsWith('(', 1)
				? TemporalType.SequenceSet
				: TemporalType.InstantSet;
		}
		return TemporalType.Instant;
	}
}

/**
 * Abstract base class for all MEOS temporal types (TBool, TInt, TFloat, …).
 *
 * Wraps a raw WASM linear memory address (_inner) pointing to a MEOS
 * temporal object. Concrete subclasses provide value-type-specific
 * operations (startValue, endValue, toString, arithmetic, comparisons…).
 *
 * Memory contract: the caller that constructs a Temporal instance owns the
 * underlying MEOS allocation. Call t.free() (or use the `using` keyword)
 * when the value is no longer needed to avoid WASM heap leaks.
 *
 * @typeParam V - The base value type (boolean for TBool, number for TInt/TFloat, …)
 */
export abstract class Temporal<V> {
	protected readonly _inner: Ptr;

	constructor(inner: Ptr) {
		this._inner = inner;
	}

	/** Starting value of the temporal. Implemented by each concrete subclass. */
	abstract startValue(): V;

	/** Ending value of the temporal. Implemented by each concrete subclass. */
	abstract endValue(): V;

	/**
	 * Wraps a raw pointer of the same concrete subtype.
	 *
	 * Used internally by methods that produce a new instance (copy, instants,
	 * restrictions, …) so that the caller receives the correct subtype without
	 * knowing the concrete class.  Each subclass implements this as
	 * `return new SubClass(inner) as this`.
	 */
	protected abstract _fromInner(inner: Ptr): this;

	/** Raw WASM pointer. Use when passing this value to low-level functions. */
	get inner(): Ptr {
		return this._inner;
	}

	/**
	 * Frees the underlying MEOS allocation.
	 *
	 * After calling free(), the instance must not be used. Calls the
	 * hand-written meos_free wrapper from res/bindings_c_header.txt.
	 */
	free(): void {
		call<void>('meos_free', null, [ptrArgType()], [ptrArgVal(this._inner)]);
	}

	/**
	 * Explicit Resource Management support.
	 * Allows `using t = TBool.fromString(...)` to free automatically.
	 */
	[Symbol.dispose](): void {
		this.free();
	}

	/**
	 * Returns a deep copy of this temporal value.
	 * MEOS: temporal_copy
	 */
	copy(): this {
		return this._fromInner(
			callPtr('temporal_copy_w', [ptrArgType()], [ptrArgVal(this._inner)])
		);
	}

	/**
	 * Returns the hex-encoded WKB representation.
	 *
	 * Uses the hand-written temporal_as_hexwkb_w wrapper which internally
	 * passes variant=4 (extended WKB) and discards size_out.
	 *
	 * MEOS: temporal_as_hexwkb
	 */
	asHexWKB(): string {
		return call<string>(
			'temporal_as_hexwkb_w',
			'string',
			[ptrArgType()],
			[ptrArgVal(this._inner)]
		);
	}

	/**
	 * Returns the MF-JSON representation.
	 *
	 * The hand-written wrapper converts an empty srs string to C NULL so that
	 * callers can omit the SRS without passing a null pointer directly.
	 *
	 * MEOS: temporal_as_mfjson
	 *
	 * @param withBbox  Include bounding box in the output (default true)
	 * @param flags     Output flags (default 3)
	 * @param precision Coordinate decimal precision (default 6)
	 * @param srs       Spatial Reference System string, or null to omit
	 */
	asMFJSON(withBbox = true, flags = 3, precision = 6, srs: string | null = null): string {
		return call<string>(
			'temporal_as_mfjson_w',
			'string',
			[ptrArgType(), 'number', 'number', 'number', 'string'],
			[ptrArgVal(this._inner), withBbox ? 1 : 0, flags, precision, srs ?? '']
		);
	}

	/**
	 * Returns the interpolation mode of this temporal value.
	 * MEOS: temporal_interp
	 */
	interpolation(): TInterpolation {
		return TInterpolation.fromString(
			call<string>(
				'temporal_interp_w',
				'string',
				[ptrArgType()],
				[ptrArgVal(this._inner)]
			)
		);
	}

	/**
	 * Returns the number of distinct instants in this temporal value.
	 * MEOS: temporal_num_instants
	 */
	numInstants(): number {
		return call<number>(
			'temporal_num_instants_w',
			'number',
			[ptrArgType()],
			[ptrArgVal(this._inner)]
		);
	}

	/**
	 * Returns the first instant as a new instance of the same subtype.
	 * MEOS: temporal_start_instant
	 */
	startInstant(): this {
		return this._fromInner(
			callPtr('temporal_start_instant_w', [ptrArgType()], [ptrArgVal(this._inner)])
		);
	}

	/**
	 * Returns the last instant as a new instance of the same subtype.
	 * MEOS: temporal_end_instant
	 */
	endInstant(): this {
		return this._fromInner(
			callPtr('temporal_end_instant_w', [ptrArgType()], [ptrArgVal(this._inner)])
		);
	}

	/**
	 * Returns the instant with the minimum value.
	 * MEOS: temporal_min_instant
	 */
	minInstant(): this {
		return this._fromInner(
			callPtr('temporal_min_instant_w', [ptrArgType()], [ptrArgVal(this._inner)])
		);
	}

	/**
	 * Returns the instant with the maximum value.
	 * MEOS: temporal_max_instant
	 */
	maxInstant(): this {
		return this._fromInner(
			callPtr('temporal_max_instant_w', [ptrArgType()], [ptrArgVal(this._inner)])
		);
	}

	/**
	 * Returns the n-th instant (0-based index).
	 *
	 * Uses the hand-written temporal_instant_n_w wrapper which converts the
	 * 0-based JS index to the 1-based index expected by MEOS internally.
	 *
	 * MEOS: temporal_instant_n
	 */
	instantN(n: number): this {
		return this._fromInner(
			callPtr(
				'temporal_instant_n_w',
				[ptrArgType(), 'number'],
				[ptrArgVal(this._inner), n]
			)
		);
	}

	/**
	 * Returns the number of distinct timestamps.
	 * MEOS: temporal_num_timestamps
	 */
	numTimestamps(): number {
		return call<number>(
			'temporal_num_timestamps_w',
			'number',
			[ptrArgType()],
			[ptrArgVal(this._inner)]
		);
	}

	/**
	 * Returns the first timestamp as microseconds since 2000-01-01 UTC.
	 * MEOS: temporal_start_timestamptz
	 */
	startTimestamp(): TimestampTz {
		return Number(
			call<bigint>(
				'temporal_start_timestamptz_w',
				'bigint',
				[ptrArgType()],
				[ptrArgVal(this._inner)]
			)
		);
	}

	/**
	 * Returns the last timestamp as microseconds since 2000-01-01 UTC.
	 * MEOS: temporal_end_timestamptz
	 */
	endTimestamp(): TimestampTz {
		return Number(
			call<bigint>(
				'temporal_end_timestamptz_w',
				'bigint',
				[ptrArgType()],
				[ptrArgVal(this._inner)]
			)
		);
	}

	/**
	 * Returns the total duration as a number of milliseconds.
	 *
	 * Uses the hand-written temporal_duration_us_w wrapper which converts
	 * the MEOS Interval* return value to a plain int64 (total microseconds).
	 * The result is divided by 1000 to return milliseconds.
	 *
	 * Pass ignoreGaps=true to sum only sequence durations, ignoring the time
	 * gaps between sequences in a SequenceSet.
	 *
	 * MEOS: temporal_duration
	 */
	durationMs(ignoreGaps = false): number {
		return (
			call<number>(
				'temporal_duration_us_w',
				'number',
				[ptrArgType(), 'number'],
				[ptrArgVal(this._inner), ignoreGaps ? 1 : 0]
			) / 1000
		);
	}

	/**
	 * Pointer-based identity check.
	 * For value equality, use the generated teq_* / temporal_eq functions.
	 */
	equals(other: Temporal<V>): boolean {
		return this._inner === other._inner;
	}

	toString(): string {
		return `${this.constructor.name}(inner=0x${this._inner.toString(16)})`;
	}
}
